### PR TITLE
Fixed VIVE Pro pid

### PR DESCRIPTION
**Pull request by mortaas**

### CODE REVIEW

**Comment by cnlohr** [comment]
Is it possible there may be two pids for Vive Pros?  Depending on the vive pro and firmware?

**Comment by mortaas** [comment]
I don't know. Here is what I do know though..

The output from lsusb -v:
https://pastebin.com/wBi9f6YJ

and the serial number of my VIVE Pro HMD is LHR-F193057D

**Comment by jdavidberger** [comment]
The main issue now seems to be getting the new config file compression working. Attaching the output -- it's no longer libz it looks like. 
[new_config_file_stream.zip](https://github.com/cnlohr/libsurvive/files/2822861/new_config_file_stream.zip)

**Comment by cnlohr** [comment]
Hmm... I find that surprising... maybe something is corrupt about how we are getting the data?

**Comment by jdavidberger** [comment]
I think you might be right; it seems like it worked in HIDAPI but not in libusb. Will dive into it more later

**Comment by jdavidberger** [comment]
Vive pro is in and should be working. I think the commit as posted had a mix of the VID from htc and the PID from valve. The LSUSB info matches generation 2 trackers though, and should work fully in the current library.

**Pull request closed without merging**
