### PR TITLE
config loading stuff

### PR DESCRIPTION
**Pull request by ChristophHaag**
Not sure if you want to merge that but it works fine here.

### CODE REVIEW

**Comment by jdavidberger** [comment]
I'll look at this tomorrow. I don't want to merge it before testing it locally first

**Comment by ChristophHaag** [comment]
Yea I already noticed an error. :)

**Comment by jdavidberger** [comment]
Can you test / look at feature/async_dev_config? 

I should have asked -- you are using the libusb compile time option right?

**Comment by ChristophHaag** [comment]
Recent commits on master are much better than this. :)

**Pull request closed without merging**
